### ISSUE TITLE
zxcvbn-server

### ISSUE THREAD

**Issue by ebeeson** [dropbox/zxcvbn#110]
Sorry, this isn't really an issue; more of just an FYI.

I want to use `zxcvbn` from a server-side Java application. It worked to load it with [Nashorn](http://www.oracle.com/technetwork/articles/java/jf14-nashorn-2126515.html), but compilation took over a minute, and the memory footprint was substantial.

Instead, I built a tiny node app to expose it as a web service: [zxcvbn-server](https://github.com/shelv-es/zxcvbn-server), along with wrappers for calling it from [Java](https://github.com/shelv-es/zxcvbn-remote-java) and [PHP](https://github.com/shelv-es/zxcvbn-remote-php).

There's obvious disadvantages to running it this way: higher runtime latency, sending passwords over the wire, etc. But the advantage is it's usable from any language that has HTTP, and there's also the benefit of not having to send the full `zxcvbn` lib over the wire.

As a demonstration of `zxcvbn-server`, I have a public instance running at [password.wtf](https://password.wtf).

Might there be any interest in zxcvbn-as-a-webservice being officially supported?

**Comment by lowe** [comment]
Hey Erik, sorry for the delay, this is cool! 

I think it's unlikely that other sites would send their users' passwords to a stand-alone service outside of their control. That's why I try to focus on client-side estimation w/ a small, downloadable library that doesn't require service calls. I haven't heard many complaints about the download size; the current global bandwidth average according to Akamai in Q3 2015 is about 5Mbps, and the estimator can be downloaded in the background. 

You might also want to check out [zxcvbn4j](https://github.com/nulab/zxcvbn4j) which is an unofficial but up-to-date port. 

Dan
