### ISSUE TITLE
Password substring stronger than password

### ISSUE THREAD

**Issue by devinrsmith** [dropbox/zxcvbn#112]
From a user interface perspective while typing in a password, I would expect the score to be non-decreasing... ie, the password meter never goes down as I type new characters. Technically as well, a substring should never have more entropy than the string.

While testing "correcthorsebatterystaple" (via meter on https://www.dropbox.com/register), the password jumped from Good to So-so between "correcthorsebatte" and "correcthorsebatter". I understand the technical reasons why the entropy goes lower as it hits a known word given the current algorithm. I think there is some potential room for improvement in this regard.

**Comment by lowe** [comment]
Hey @devinrsmith, while different from other ranking algorithms and potentially confusing to users (hence zxcvbn's verbal feedback which can help), I disagree that substrings should necessarily have less entropy than strings.

For example, consider `elephant`, which zxcvbn ranks as the 275th most common password in the Xato 10M password corpus. Crackers generally iterate through common passwords first (say up to a dictionary size of 10k, 100k, 1M) before applying mangling rules such as trying substrings -- otherwise they'd need to make many more guesses before getting to the most likely passwords. Operating under that threat model: 

 `elephan` and `elepha` should both be stronger than  `elephant`.  

A weakness of zxcvbn is it doesn't recognize edit distance from dictionary words -- it analyzes `elepha` as a bruteforce match, for example, vs a mangling of `elephant`. Even if it had that capability I would still give higher weight to `elepha` (add guesses for mangling). 

(Other small note is that zxcvbn ranks `elephan` as a common password with rank 12828 vs 275, because it too is a common password, but less common than `elephant`.)

I'd still be interested to hear ideas if you have them on how to make this better, or user interface-level ideas that make it less confusing to people.

**Comment by devinrsmith** [comment]
Yeah, the key thing here is we are assuming a threat model to assign entropy (ie: given a password cracking algorithm, how long until we generate the given password). The problem is that the current state of the "threat model" changes over time as users' password preferences change and password crackers update algorithms. Of course, we have to make assumptions somewhere... 

Anyways, I think it's still a valid concern from a UI point of view. I don't have any solutions to offer though!
