### ISSUE TITLE
"correcthorsebatterystaple" should not be considered very secure

### ISSUE THREAD

**Issue by emragins** [dropbox/zxcvbn#146]
Due to the popularity of a [comic we all know and love](https://xkcd.com/936/), "correcthorsebatterystaple" has become the epitome of a secure password, but it's very popularity makes it insecure.  If I were into cracking passwords, it would be in my "must try" list.

Can it make it to the naughty list? :)

**Comment by tracker1** [comment]
Couldn't you add it to the common words dictionary?

**Comment by nicholasss** [comment]
What if there was a 'cultural significance' dataset that it could pull common words and numbers from, such as correcthorsebatterystaple, or 911, 1776 etc

**Comment by galaara98** [comment]
i agree with the OP, but it could also be solved if each installation had a Institutional Dictionary...
i would like to be able to add different words to a Dictionary, at will, for all users without touching the provided dictionaries.  (because i want to sync them against some source of truth, so i don't want customized content in them)  This is different then the benefit of the on the parameter that allows incidental for "this user" dictionary words.

**Comment by lowe** [comment]
Hi all, 

Though popular within our subculture, It feels kludgy to include one-offs like this by default. If you know of any recent leaks where `correcthorsebatterystaple` is a top password (say, one of the most common 10 million password choices), let me know. 
 
In the meantime the optional [`user_inputs` argument](https://github.com/dropbox/zxcvbn) to zxcvbn is a great way to add this sort of capability, similar to @nicholasss's cultural significance dataset idea.   

I'm also going to make it much soon to add more custom dictionaries.
