### ISSUE TITLE
Is this still mantained?

### ISSUE THREAD

**Issue by anik786** [dropbox/zxcvbn#168]
I've noticed the last commit was in May. Is this because this code is not being maintained that well or because there hasn't been much need for updates?

**Comment by lowe** [comment]
Hi @anik786, still maintained!

Summer travel + [zxcvbn-related research](https://www.usenix.org/conference/usenixsecurity16/technical-sessions/presentation/wheeler)  has kept me busy since May, but the library is stable. That said I'll be working through bugs and pull requests soon now that the conference is over.

**Comment by anik786** [comment]
Great!

**Comment by konklone** [comment]
It's now been a year and half since any commits to the code:

<img width="1011" alt="screen shot 2018-07-18 at 1 36 18 pm" src="https://user-images.githubusercontent.com/4592/42897924-9bb62f52-8a8f-11e8-83b6-de31d0fe15c7.png">

Where is the active work going these days? Is it Dropbox-internal now, or are there newer libraries where work is being done?

**Comment by Tostino** [comment]
@konklone I am still maintaining / improving https://github.com/GoSimpleLLC/nbvcxz

It is not intended as a drop in replacement for zxcvbn, but used the ideas as a basis to build from and improve on.

Considering the popularity of zxcvbn, it is sad that it isn't being actively improved though.
