### ISSUE TITLE
Overestimates cardinality for bruteforce substrings when other types of characters present elsewhere

### ISSUE THREAD

**Issue by mechanical-snail** [dropbox/zxcvbn#17]
It seems that the cardinality used to calculate entropy of bruteforce substrings is calculated based on the entire string. For example:

`frzplfqetuothv`: cardinality 26, as expected

`frzplfqetuothvpassword`: cardinality 26, as expected

`frzplfqetuothvpasswordA`: cardinality 85.

The `A` present elsewhere in the string causes it to assume that the letters of `frzplfqetuothv` were sampled from the larger set of characters. This doesn't make sense, because users often pick passwords with e.g. a punctuation mark attached. Thus it is vastly overestimating the entropy of such passwords. The cardinality should be calculated per bruteforce substring.

Related: It parses passwords like `frzplfqetuothvCOCIWDZOAZPVRL` as one long bruteforce string. It should attempt to split such strings into multiple bruteforce runs with lower cardinality.

**Comment by lowe** [comment]
This is now fixed. Cardinality for bruteforce matches is now 10 across the board, independent of types of characters present. 

One thing is for sure -- earlier cardinality estimates were way too high. A [markov attack](https://hashcat.net/wiki/doku.php?id=statsprocessor), for example, could significantly reduce the number of tries needed per character if the password is "english word-like" [common consonant-vowel sequences] or "password-like" [starts with capital letters, lowers in the middle, ends with numbers]. 

It would be a fun future research project to investigate better models for estimating resistance to markov attacks / other "smart" bruteforce attacks on a given password, perhaps trained on a large password corpus. For now this is a simple fix in the right direction. 

One downside is this significantly underestimates the guessability of long random strings. A random alphanumeric string will get estimated as 10^n instead of 62^n, for example. Yet another case of underestimating to be safe.
