### ISSUE TITLE
Out of the box issues

### ISSUE THREAD

**Issue by holyfirexx** [dropbox/zxcvbn#170]
Hello, 

I was recently looking into using zxcvbn for a project I am working on however, to my surprise it is seemingly broken right out of the box. I downloaded the zip of the project and started off installing node, npm, git, bower , coffeescript, browserify and uglify. After that I ran "npm run build" and discovered multiple problems.

Just to name a few, in the package.json on my system(Windows 7) src/*.coffee does not work, it has to be src/. The "build" option under scripts is `"build": "npm run build-lib ; npm run build-dist", `but it seems like it should be `"build": "npm run build-lib & npm run build-dist",` and for build-dist `"build-dist": "browserify --debug  --standalone zxcvbn -t coffeeify --extension='.coffee' -t uglifyify src/main.coffee |   exorcist dist/zxcvbn.js.map >| dist/zxcvbn.js",` it breaks because of an unexpected |. Removing the second pipe fixes the issue. 

Throughout all the .coffee files the requires are `=('./<somefile>')` but that resulted in an error. They only worked if I changed it too `=('./<somefile>.coffee')`. 

Also, the zuul dependency is broken as it requires stacktrace.js and the link zuul uses to find it is broken. I had to download the zuul package myself to get past this issue. 

Did I just do something terribly wrong or had these bugs not been discovered yet? 

Thanks for any input!

**Comment by lowe** [comment]
Hi @holyfirexx,

This sounds like a shell issue to me, since you mentioned Windows 7. These build scripts assume a UNIX/bash environment. 

What terminal emulator are you using on Windows? So long as you choose something bash-compliant, it should work out of the box. 

A few followups: 

**src/*.coffee** does not work -- sounds to me like * isn't being recognized as a bash wildcard. 

**>|** -- see [Redirections](http://www.gnu.org/software/bash/manual/bashref.html#Redirections) from the bash manual. 

**";" vs "&"** -- either is correct with slightly different meaning. I chose ";" because they're independent build steps. (With "&", the second command won't run if the first fails.)

**requiring ./somefile vs ./somefile.coffee** -- Node searches for somefile.js when the suffix isn't specified. Tiny detail, but I left the file extension off to allow alternate command-line tools such as coffeenode, which will automatically pick up somefile.coffee instead.

**Comment by holyfirexx** [comment]
@lowe Ah! Of course. Honestly, I was unaware that it required bash. Perhaps this could be added to the read me. 

It is odd though, I started running it in a bash, (Git Bash was all I had on hand.) and it still isn't working. It seems like perhaps npm is running it without bash even though I'm calling it from a bash-compliant terminal. I tested git bash to be sure and it recognizes src/*.coffee but when I run npm run build I still get the errors. I have hardly used npm so there is still a few things I need to learn!

**Comment by tracker1** [comment]
@holyfirexx I had similar issues in windows... IIRC, I'd worked around them in my fork, but it's *WAY* behind mainline now, that it'd be easier to just re-do the adjustments to get build working in windows.

**Comment by holyfirexx** [comment]
@tracker1 I was able to get my copy working with the changes I mentioned above. I was just wondering if /hoping I was doing something wrong and I could make the process a little easier if I or any of my co-workers need to do it again.

**Comment by mgw854** [comment]
Forgive me if I'm mistaken, but I'm using zxcvbn in a project, and I just ran `npm install --save zxcvbn` and had everything ready to go. I don't think you have to build from source.

**Comment by holyfirexx** [comment]
You are correct, if you aren't making any changes. I am modifying a couple things in zxcvbn so I needed to build it from source.
