### ISSUE TITLE
Inconsistent results when going from 2 to 3 digits

### ISSUE THREAD

**Issue by nylen** [dropbox/zxcvbn#37]
The library says that `word781` has less entropy than `word78`, because `781` is identified as `digits` but `78` is identified as `bruteforce` with lower entropy:

```
password:	word78
entropy:	20.928
crack time (seconds):	99.743
crack time (display):	3 minutes
score from 0 to 4:	    0
calculation time (ms):	0
```

```
password:	word781
entropy:	18.677
crack time (seconds):	20.95
crack time (display):	instant
score from 0 to 4:	    0
calculation time (ms):	1
```

**Comment by lowe** [comment]
Thanks for reporting -- the jump from 2 to 3 digits was fixed in version 3.3.0 and up. zxcvbn used to skip 2-character substrings for several of its patterns, and that behavior has since been removed. 

Additionally, a new regex matcher now matches digit regions as well as other common regex patterns. 

Try:  
https://dl.dropboxusercontent.com/u/209/zxcvbn/test/index.html
