### ISSUE TITLE
Detect and account for repeated choices

### ISSUE THREAD

**Issue by azul** [dropbox/zxcvbn#53]
There's a number of examples of overestimated entropies for passwords like these:
"ekekekekek", " . . . . . " (#39). Also space seperated passwords ("dark and stormy night") get quite a high entropy(#21).

I think this is because the algorithm does not detect higher level repetition patterns. For space separated strings it's okay that it does not take into account that there is a repetition of <pre>(dictionaryword)(bruteforce)</pre> because the algorithm ignores the entropy in that information anyway. The problem is that it does not recognize that always the same selection is picked within a given searchspace. To illustrate this... you get an even higher entropy for "dark dark dark dark".

So when calculating the entropy a selection that occures n times should add ln(n) plus the entropy of the selection itself instead of n times the entropy of the selection itself. This should probably be applied before picking the lowest entropy.

**Comment by lowe** [comment]
thanks for reporting -- multi-character repeats are fixed in 3.5.0. 

overestimating extra entropy for spaced passwords "dark and stormy night" is coming soon in another release -- a noted flaw for sure! to address that problem currently what i'm thinking is: when spaces are present, run zxcvbn on spaced and non-spaced variants, and return the minimum entropy.  something along those lines. similar treatment for dash- and underscore-separated patterns.

**Comment by MacMadame** [comment]
How about returning the average? My thinking is that adding separators does increase entropy over not having them.
