### ISSUE TITLE
Singe characters match dictionaries

### ISSUE THREAD

**Issue by martinstuecklschwaiger** [dropbox/zxcvbn#61]
It's quite strange, that single characters match dictionaries:
`a` has an entropy of `2.33` whereas `i` has an entropy of `1` because it is matched by the dictionary. 

The same problem exists with single digits: 
`1`(entropy = 2) and `4` (entropy = 3.32( match a dictionary, whereas the other single digits have an entropy of 5.42.

**Comment by lowe** [comment]
Hi @martinstuecklschwaiger, it's been a while but thanks for posting this issue :) 

One way to fix would be to disallow single-character dictionary matches. But for passphrases like:  

iwantapony 

I do think 'i' and 'a' should be matched as words, so I likely won't outlaw single-character dictionary matches. 

I'm considering disallowing l33t substitutions for single-character words. That fixes the '1' and '4' case without much loss. 

There's one more problem related to another issue that I am fixing soon (related to issue #48 ): 
even though `password1` is a very common password, `password1` gets matched as `password` + `1`, with `1` being matched as `i` with a substitution.

This is because zxcvbn currently adds no penalty for 2-pattern matches (`password` + `1`) vs 1-pattern matches (`password1`), and `password` is even more common than `password1`. Fixing that issue will also reduce this problem.

**Comment by dbakker** [comment]
> I do think 'i' and 'a' should be matched as words, so I likely won't outlaw single-character dictionary matches.

If you count them as dictionary words, shouldn't their entropy be even higher than single letters? (E.g. from a dictionary of 7000 the entropy of the word 'a' would be: log(7000, 2) = 12.8.) Would it be significantly easier to crack `iwantapony` than `zwantxpony`?

| password | guesses_log10 | status |
| --- | --- | --- |
| `a6a4Aa8a` | 9.18 | so so |
| `b6b4Bb8b` | 10.64 | good |
| `z6z4Zz8z` | 13.55 | great |
| `aiIiAaIA` | 9.81 | weak |
| `zxXxZzXZ` | 13.04 | great |

In my *non-expert* opinion it feels like all these passwords should be about even in strength.

**Comment by lowe** [comment]
Thanks to a new sequence length penalty in the minimum entropy search function, this issue is now resolved. All the patterns in @dbakker's table now have the same score. 

@dbakker -- zxcvbn assigns entropy to words based on how common those words are. 'a' and 'i' are top-10 words, hence the low score, given small dictionaries would include them.
