### ISSUE TITLE
Publish it to npm

### ISSUE THREAD

**Issue by binarykitchen** [dropbox/zxcvbn#80]
Please. When you already support Bower, then why not npm too?

**Comment by binarykitchen** [comment]
I couldn't wait any longer and npm-published a fork
https://github.com/binarykitchen/zxcvbn-npm

Also made it light, without any minification and async/bower/umd loading so that it can be easily included with browserify.

**Comment by lowe** [comment]
Hi Michael, I'm working with the original npm package author now to get
access. I'll fix npm and update the readme as soon as that happens.

**Comment by lowe** [comment]
All fixed. This separate npm repo should no longer be needed but let me know if you still have outstanding issues.

**Comment by lowe** [comment]
(I also included install instructions for browserify, npm, bower, requirejs and manual.)

**Comment by ericyhwang** [comment]
One thing I noticed while updating to use the published NPM module - previously on the server, the require looked like `var zxcvbn = require('zxcvbn');`, whereas now it's `var zxcvbn = require('zxcvbn').zxcvbn;`.

I realize NPM support was previously unofficial and that the second way is now the officially documented way. Just wanted to give you a heads-up that you might be breaking people depending on `^1.0.0` and to publish a major rev if you want `require('zxcvbn').zxcvbn` to be the way going forward.

**Comment by lowe** [comment]
Hey @ericyhwang, the full story here is messy unfortunately. I originally used `exports` instead of `module.exports` in init.coffee, in order to support older CommonJS frameworks that don't recognize `module.exports` (introduced by node and not originally part of CommonJS spec). This leads to the verbose `var zxcvbn = require('zxcvbn').zxcvbn;`. 

The original publisher for the npm module added an `index.js` file that used `modue.exports` on top of my exports call, and I didn't catch it. This gives the nicer require syntax but creates an inconsistency. 

My plan going forward is to switch exclusively `module.exports` in an upcoming 2.0 release because that's the better interface moving forward -- I'd be great to shorten `var zxcvbn = require('zxcvbn').zxcvbn;` to `var zxcvbn = require('zxcvbn');`.

The v1 series will continue using `exports` for older frameworks that depend on it.
