### ISSUE TITLE
What's the breaking change between v2 and v3?

### ISSUE THREAD

**Issue by binarykitchen** [dropbox/zxcvbn#87]
This is nowhere mentioned and the reason why I hesitate to upgrade.

**Comment by tracker1** [comment]
@binarykitchen  AFAIK the default exports changed, so now you `var zxcvbn = reqoure('zxcvbn')` where as before it was exporting an object with a function attached.  That would be an incompatible change, requiring a full version bump.

Most of the changes are in the project structure/layout and removal of closure compiler in favor of uglify, which removes the Java requirement.  I wrote the suggestions up in an issue/pr a while back, and @lowe seems to have implemented most of them, with some variation.  Also, the core modules are now written with cjs/node-style exports instead of being merged inside a closure wrapper.  The structure is definitely a lot more clean and approachable now.

The only non-node/js parts remaining are the data-scripts that gather/process the data directory (these aren't run with the build/deploy).  I suspect this may, or may not be updated the next time the statistical data is updated, which probably won't be needed before 2020.

**Comment by lowe** [comment]
Breaking changes are listed in the [release notes](https://github.com/dropbox/zxcvbn/releases). @binarykitchen, for future reference where did you expect to look?

**Comment by binarykitchen** [comment]
I couldn't locate the release notes in the readme.md - can you place such a link there?

**Comment by lowe** [comment]
done, good idea

**Comment by binarykitchen** [comment]
Good boy :)

On August 10, 2015 5:39:30 PM NZST, Dan Wheeler <notifications@github.com> wrote:
>done, good idea
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dropbox/zxcvbn/issues/87#issuecomment-129311474

--

Binary Kitchen
Michael Heuberger
1/33 Parrish Road
Sandringham
Auckland 1025
(New Zealand)

Mobile (text only) ... +64 21 261 89 81
Email ................ michael@binarykitchen.com
Website .............. https://binarykitchen.com
