### ISSUE TITLE
webpack complains about v3

### ISSUE THREAD

**Issue by binarykitchen** [dropbox/zxcvbn#88]
```
WARNING in ./~/zxcvbn/lib/zxcvbn.js
Critical dependencies:
1:479-486 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/zxcvbn/lib/zxcvbn.js 1:479-486
```

this everytime it tries to build our app requiring `zxcvbn`

**Comment by lowe** [comment]
I'm new to webpack, what would you suggest to make it play nice w/ my browserify setup?

**Comment by binarykitchen** [comment]
Problem is that webpack sees the source code is already minified which isn't good.

I have to add this webpack option so that the above warning gets ignored during gulp

```
noParse: [/zxcvbn/] # Do not parse zxcvbn because it's prebuilt
```

**Comment by tracker1** [comment]
@binarykitchen you could try `require('zxcvb/src/main')` if you enable coffeescript with webpack (I don't know it well enough to know if it is an options).

@lowe maybe change `src/main.coffee` to `src/index.coffee`?  that way it could be `require('zxcvbn/src')`

**Comment by binarykitchen** [comment]
but the `/src` folder is in the .npmignore list, so that won't work. for npm modules it's recommended always to include the source code.

**Comment by lowe** [comment]
OK, I think I now have a setup that will make everyone happy. 

-- `zxcvbn.js` and `zxcvbn.js.map` now live in `dist`, not `lib`. 
-- I added a `prepublish` hook to `package.json` that compiles each `.coffee` file in `src` to a `.js` and `.js.map` file in `lib`.
-- I changed `"main"` in `package.json` to point to `lib/main.js` instead of bundled/minified code. 

All together: 

npm: includes `dist/`, `src/` and `lib/`
bower: includes `dist/`, ignores `src/` and `lib/`
git: includes `dist/` and `src/`, ignores `lib/` 

external source maps are included in both `dist` and `lib` 

@binarykitchen, can you update and try your webpack setup without the `noParse` and see if it magically works? See the README for a new browserify / webpack section. 

Decisions that I'm open to feedback on: 

-- While I don't like checking in minified code (`dist/`) to github, I want people to be able to easily grab the latest build without an npm build dependency. So what I plan to do is separate build commits from source commits to at least clean up the commit history that way. (At least compiled `lib/` code is ignored by the repo.)

-- source maps grow the package size a good amount, but help everyone debug. An alternative would be to remove source maps from the package and offer a command to generate them for those that care. 

-- I could have added `src/` to `.npmignore`, but didn't -- some coffeescript npm package maintainers just include compiled `lib/` on npm, and `src/` on github. At the cost of a fatter package, I included `src/` to make it easier to debug zxcvbn w/ the provided sourcemaps. Including `src/`, `lib/` AND `dist/` on npm may prove to be excessive.

**Comment by binarykitchen** [comment]
wonderful, i can confirm, your changes are good - thx heaps
