### ISSUE TITLE
Two-digit year date problems

### ISSUE THREAD

**Issue by tekul** [dropbox/zxcvbn#9]
I've noticed a few issues with date matching.

For example:

04052001 is matches as a date, but 040501 is not (and has higher entropy)

And with separators:

27.05.2005 - date, entropy=17.434
27.05.05 - bruteforce, entropy = 43.41

The latter, at least, seems to be due to `check_date` only accepting 4-digit years. Also, both day and year would need to be checked for the 2-digit year case to see if either is <= 31.

I also noticed that zero is accepted for days and months, though that isn't a big issue as it will at worst cause an underestimate for the entropy.

**Comment by lowe** [comment]
fixed in version 3.3.0 which includes a full rewrite of date matching + unit tests. 

scoring is conservative now: lg(12 * 31 * Math.abs(year - 2000))
 
the -2000 term is meant to give lower entropy to dates in the late 90s / early 00s, and higher entropy to more distant dates. 

1 bit of entropy is added for zero-padding. 1 bit of entropy for using four-digit years instead of two. 2 bits of entropy for using separators, idea being there's ~4 separators to choose from '/\.-' so add lg(4) == 2.
