### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by alexschneider** [dropbox/zxcvbn#98]
I tried using zxcvbn and almost none of the result properties that the documentation says are available under usage are available - only the calc_time. It looks like the final result is a bit more complex and I'm not entirely sure how to use it to implement password scoring in my application - is there any chance the documentation can be updated to reflect that?

https://github.com/dropbox/zxcvbn#usage

https://jsfiddle.net/dh0uxd12/

**Comment by lowe** [comment]
Hi @alexschneider -- the issue is I sometimes push changes to github before updating the documentation and tagging a release. 

If you use npm or bower to install zxcvbn, the documentation should match the code. 

If you use github, just update to the latest tag: 

for example: 

```
git checkout tags/3.5.0 
```

Sorry for the confusion! I'll try to avoid pushing changes w/o updating docs in the future.

**Comment by alexschneider** [comment]
@lowe Thanks for responding - I used the manual instalation steps here: https://github.com/dropbox/zxcvbn/#manual-installation

Perhaps the link can be linked to the latest tag rather than to master?

**Comment by lowe** [comment]
That's a great idea -- I'll do that next time I update the docs.

-Dan
